# Required to run your project under the correct environment.
language: php
php:
  - nightly

# Versions of PHP you want your project run with.
php:
  - 5.4
  - 5.5
  - 5.6
  # - hhvm

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev


# Commands you want to run that will verify your build.
script: vendor/bin/phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.

sudo: false

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
    env:- DB=pgsql
        - APP_ENV=testing
        - APP_DEBUG=true
        - APP_KEY=lEJl3EPdPaXthdJvLE6sJFUIpYO1hHe0
