before_script: 
  - "composer self-update"
  - "composer install --prefer-source --no-interaction --dev"
language: php
matrix:
  ? "allow_failures:- php"
  : 5.5
  fast_finish: true
notifications:
  env: "DB=pgsql - APP_ENV=testing - APP_DEBUG=true - APP_KEY=lEJl3EPdPaXthdJvLE6sJFUIpYO1hHe0"
  on_failure: always
  on_success: never
php:
  - 5.4
  - 5.5
  - 5.6
script: vendor/bin/phpunit
sudo: false
