language: php

php:
  - 5.5

matrix:
  include:
    - php: 5.5
      env: setup=lowest
    - php: 5.5
      env: setup=stable
  fast_finish: true

sudo: false

services:
  - redis-server

before_install:
    - composer dump-autoload
    - composer self-update

script: /vendor/bin/phpunit
